FROM python:3.10.13-slim

ENV OS_ENV=LINUX
ENV RUNTIME_ENV=DOCKER

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python"]
CMD ["app.py"]