FROM python:3.10.13-slim

ENV OS_ENV=LINUX
ENV RUNTIME_ENV=DOCKER

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 6900

ENTRYPOINT ["gunicorn"]
CMD ["-b", "0.0.0.0:6900", "--workers=2", "app:app"]