name: Trigger auto deployment for pam-data-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pam-data-api-AutoDeployTrigger-39d2c098-fcaa-42e4-b7a0-f52b81d8963d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PAMDATAAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PAMDATAAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PAMDATAAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PAMAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Copy from file storage
        env:
            AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
            AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        run: | 
          az storage blob download \
          --account-name $AZURE_STORAGE_ACCOUNT \
          --container-name $AZURE_STORAGE_CONTAINER \
          --name .env.api \
          --file ./.env \
          --auth-mode login



      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile-azure
          registryUrl: docker.io
          registryUsername: ${{ secrets.PAMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PAT }}
          containerAppName: pam-data-api
          resourceGroup: pam-apis
          imageToBuild: generaliroh/general-project-repo:pam_data_api
          _buildArgumentsKey_: |
            _buildArgumentsValues_


