name: Trigger auto deployment for pam-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pam-api-AutoDeployTrigger-9a641fba-db96-4288-b5d9-eb6dfe2ea00c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PAMAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PAMAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PAMAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.PAMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PAMAPI_REGISTRY_PASSWORD }}
          containerAppName: pam-api
          resourceGroup: pam
          imageToBuild: hub.docker.com/pam-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


